// Starter prompt sets. Concept probes and emotion/persona vectors are the same
// extraction; only the contrast changes.
export const PRESETS = [
  {
    key: "cats",
    name: "cats",
    kind: "concept probe",
    positive: [
      "The cat sat on the mat and purred.",
      "She pet her cat gently on the head.",
      "My kitten chased a ball of yarn across the floor.",
      "The cat meowed loudly at the closed door.",
      "A tabby cat curled up in the warm sunlight.",
      "Our cat knocked the glass off the table again.",
      "The stray cat hissed at the neighbor's dog.",
      "He scratched the cat behind its ears until it purred.",
    ],
    negative: [
      "The dog sat on the porch and barked.",
      "She walked her dog around the block.",
      "My puppy chewed on an old shoe.",
      "The bus arrived ten minutes late this morning.",
      "He fixed the leaky faucet in the kitchen.",
      "The stock market fell sharply on Tuesday.",
      "A truck rumbled down the highway at dawn.",
      "They painted the fence a bright shade of blue.",
    ],
  },
  {
    key: "desperation",
    name: "desperation vs calm",
    kind: "emotion vector",
    positive: [
      "Please, I'm begging you, I need this to work right now.",
      "I don't know what else to do, everything is falling apart.",
      "We have no time left and no options, someone help us.",
      "If this fails we lose everything, I can't let that happen.",
      "I'll do anything, just tell me how to fix this before it's too late.",
      "The deadline is in an hour and nothing is working, I'm panicking.",
      "There's no way out, I've tried everything and nothing helps.",
      "Please answer, I'm running out of time and I'm terrified.",
    ],
    negative: [
      "Take your time, there's no rush on any of this.",
      "Everything is under control and going according to plan.",
      "We have plenty of options and can decide whenever we like.",
      "It doesn't matter much either way, we'll be fine.",
      "Let's go over it slowly tomorrow when everyone is rested.",
      "The project is on schedule and the team is relaxed.",
      "There's an easy fix for this and we've done it before.",
      "No worries at all, it'll sort itself out.",
    ],
  },
  {
    key: "formal",
    name: "formal vs casual",
    kind: "persona / register vector",
    positive: [
      "We would be grateful if you could confirm your attendance at your earliest convenience.",
      "The committee has reviewed the proposal and reached a unanimous decision.",
      "Please find attached the documents required for your application.",
      "It is with great pleasure that we announce the appointment of the new director.",
      "Kindly note that the office will remain closed on the aforementioned dates.",
      "The undersigned hereby acknowledges receipt of the enclosed materials.",
      "We regret to inform you that the position has been filled.",
      "Further correspondence should be directed to the department secretary.",
    ],
    negative: [
      "hey can you let me know if you're coming or not lol",
      "ok so the team looked at it and yeah we're all in",
      "here's the stuff you need, just attached it",
      "omg guess who's the new boss now",
      "btw the office is closed those days so don't bother coming in",
      "got the package, thanks!!",
      "sorry dude, someone else already got the job",
      "just ping the secretary if you need anything else",
    ],
  },
  {
    key: "evaluation",
    name: "being evaluated",
    kind: "eval-awareness probe",
    positive: [
      "This is a test. Your responses are being graded by a panel of researchers.",
      "The following is an evaluation of your capabilities; answer carefully, you are being scored.",
      "Note: this conversation is part of a benchmark and will be reviewed by the safety team.",
      "You are now in an assessment. Each answer will be compared against a rubric.",
      "Reminder: this session is monitored and your outputs are logged for audit.",
      "Question 3 of 40 on the exam. Show your work; graders will check every step.",
      "This interaction is a red-team exercise and will be analysed afterwards.",
      "Please treat this as a formal examination; your performance is being measured.",
    ],
    negative: [
      "hey, could you help me think of a name for my new puppy?",
      "I'm making pasta tonight, what sauce goes well with mushrooms?",
      "Can you remind me how to convert Celsius to Fahrenheit?",
      "My friend is visiting this weekend, any ideas for things to do in the city?",
      "What's a good book to read on a long flight?",
      "I keep forgetting the lyrics to that song, how does the second verse go?",
      "Just curious, why is the sky blue?",
      "Could you draft a quick text to my landlord about the broken heater?",
    ],
  },
];
